trigger:
- master

pool:
  name: Sonarqube-Agent

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '9.0.x'

steps:
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'Sonarqube'
    scannerMode: 'dotnet'
    projectKey: 'Vlead-dotnet-ui'

- task: UseDotNet@2
  displayName: 'Install .NET 9.0'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore Dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'